'''
Simple Welcome Banner by Matthew Wang
Uses sleep + clear, creates a 3 second Welcome loading symbol
Clear function courtesy of Stackoverflow.
'''
#import libraries
import os
import time
#clear function
def cls():
	os.system(['clear','cls'][os.name == 'nt'])
#main, just prints and clears
def welcome():
	cls()
	print("____    __    ____ ")
	print("\   \  /  \  /   / ")
	print(" \   \/    \/   /  ")
	print("  \            /   ")
	print("   \    /\    /    ")
	print("    \__/  \__/     ")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______ ")
	print("\   \  /  \  /   / |   ____|")
	print(" \   \/    \/   /  |  |__   ")
	print("  \            /   |   __|  ")
	print("   \    /\    /    |  |____ ")
	print("    \__/  \__/     |_______|")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______  __      ")
	print("\   \  /  \  /   / |   ____||  |     ")
	print(" \   \/    \/   /  |  |__   |  |     ")
	print("  \            /   |   __|  |  |     ")
	print("   \    /\    /    |  |____ |  `----.")
	print("    \__/  \__/     |_______||_______|")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______  __        ______ ")
	print("\   \  /  \  /   / |   ____||  |      /      |")
	print(" \   \/    \/   /  |  |__   |  |     |  ,----'")
	print("  \            /   |   __|  |  |     |  |     ")
	print("   \    /\    /    |  |____ |  `----.|  `----.")
	print("    \__/  \__/     |_______||_______| \______|")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______  __        ______   ______   ")
	print("\   \  /  \  /   / |   ____||  |      /      | /  __  \  ")
	print(" \   \/    \/   /  |  |__   |  |     |  ,----'|  |  |  | ")
	print("  \            /   |   __|  |  |     |  |     |  |  |  | ")
	print("   \    /\    /    |  |____ |  `----.|  `----.|  `--'  | ")
	print("    \__/  \__/     |_______||_______| \______| \______/  ")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______  __        ______   ______   .___  ___. ")
	print("\   \  /  \  /   / |   ____||  |      /      | /  __  \  |   \/   | ")
	print(" \   \/    \/   /  |  |__   |  |     |  ,----'|  |  |  | |  \  /  | ")
	print("  \            /   |   __|  |  |     |  |     |  |  |  | |  |\/|  | ")
	print("   \    /\    /    |  |____ |  `----.|  `----.|  `--'  | |  |  |  | ")
	print("    \__/  \__/     |_______||_______| \______| \______/  |__|  |__| ")
	time.sleep(0.5)
	cls()
	print("____    __    ____  _______  __        ______   ______   .___  ___.  _______ ")
	print("\   \  /  \  /   / |   ____||  |      /      | /  __  \  |   \/   | |   ____|")
	print(" \   \/    \/   /  |  |__   |  |     |  ,----'|  |  |  | |  \  /  | |  |__   ")
	print("  \            /   |   __|  |  |     |  |     |  |  |  | |  |\/|  | |   __|  ")
	print("   \    /\    /    |  |____ |  `----.|  `----.|  `--'  | |  |  |  | |  |____ ")
	print("    \__/  \__/     |_______||_______| \______| \______/  |__|  |__| |_______|")
	time.sleep(0.5)

welcome()
